<?xml version="1.0" encoding="utf-8"?>
<Project>

  <Target Name="WpfHelperAddFiles" BeforeTargets="BeforeCompile">
    <PropertyGroup>
      <WhThisDir>$(MSBuildThisFileDirectory)</WhThisDir>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="$(WhThisDir)Commands/AbstractSimpleCommand.cs" />
      <Compile Include="$(WhThisDir)Commands/INotifyCanExecuteChanged.cs" />
      <Compile Include="$(WhThisDir)Commands/SimpleCommand.cs" />

      <Compile Include="$(WhThisDir)Controls/ScrollFrameworkElementBase.cs" />

      <Compile Include="$(WhThisDir)Data/BindableBase.cs" />
      <Compile Include="$(WhThisDir)Data/IntToBoolConverter.cs" />

      <Compile Include="$(WhThisDir)ViewModels/ViewModelBase.cs" />
    </ItemGroup>
  </Target>

</Project>
