<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Commands/AbstractSimpleCommand.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Commands/INotifyCanExecuteChanged.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)Commands/SimpleCommand.cs" />

    <Compile Include="$(MSBuildThisFileDirectory)Controls/ScrollFrameworkElementBase.cs" />

    <Compile Include="$(MSBuildThisFileDirectory)Data/IntToBoolConverter.cs" />

    <Compile Include="$(MSBuildThisFileDirectory)ViewModels/ViewModelBase.cs" />
  </ItemGroup>

</Project>
